### PR TITLE
[C++] Attach new schema update when update dataset

### PR DESCRIPTION
**Pull request by eddyxu**
Supplement metadata key-value pairs for Schema when updating a dataset.

### CODE REVIEW

**Review by changhiskhan — COMMENTED** [review]
What's the use case for this extra metadata?
If it's for version tagging, then it shouldn't be part of the schema right?
If it's for adding schema-specific metadata in a particular version -- would it make sense to add it for row appends as well?

**Comment by eddyxu** [comment]
> If it's for adding schema-specific metadata in a particular version -

So here, (due to the schema evolution), each version will have a separate schema. Do you feel it needs a separate k/v metadata for the versions as well?

> would it make sense to add it for row appends as well?

Sure, lemme add the metadata to `Dataset::Write` and expose them via `DatasetVersion`?

**Comment by eddyxu** [comment]
The notebook error was due to the incompatible format changes.

**Review by changhiskhan — APPROVED** [review]
are tests failing because we need to regenerate the dataset?

**Pull request merged**
