### PR TITLE
expand tilde paths in python

### PR DESCRIPTION
**Pull request by ananis25**
Resolves issue #619 . 

### Current behavior:
On Posix systems (tested on Mac), this creates a subdirectory in the current directory, instead of resolving to the user's home directory. 
```py
addr = "~/foo.lance"
df = pd.DataFrame({"colA": [1, 2, 3], "colB": [4, 5, 6]})
lance.write_dataset(df, addr)
```
At read time, it tries to read off the current directory again. 

### Expected behavior: 
Treat `~` prefix as pointing to the user's home directory. 

### Notes:
- The error is related to tilde expansion, which is really a bash feature. Python doesn't handle these by default either. 
```py
with open("~/moo.txt", "w") as f:
    f.write("hello\n")

# FileNotFoundError: [Errno 2] No such file or directory: '~/moo.txt'
```

- The PR uses a python stdlib function to handle expanding these paths. This is also used in pandas - [link](https://github.com/pandas-dev/pandas/blob/d08d4510db5e79b8e65b35174a3bc3a968bb9189/pandas/io/common.py#L183). 

- This can also be handled in rust but would require another third party dep - [link](https://crates.io/crates/expanduser/1.2.2).

### CODE REVIEW

**Comment by eddyxu** [comment]
Should we do the fix in Rust tho, so all language bindings in the future can share the same behavior?

**Comment by changhiskhan** [comment]
> Should we do the fix in Rust tho, so all language bindings in the future can share the same behavior?

could use https://crates.io/crates/shellexpand perhaps?

**Comment by ananis25** [comment]
I was trying to avoid rust to not introduce more dependencies, but consistency is a good point. I'll make the change.

**Comment by ananis25** [comment]
Moved handling of tilde in path strings to rust. 

Note, the rust code already handled expanding relative paths to absolute paths, so the python function call to do it was unnecessary. This also removes it.

**Comment by changhiskhan** [comment]
> Moved handling of tilde in path strings to rust. 
> 
> 
> 
> Note, the rust code already handled expanding relative paths to absolute paths, so the python function call to do it was unnecessary. This also removes it. 

Does this mean tilde expansion should already work? How come there's an exception raised in this instance?

**Comment by ananis25** [comment]
So, `tilde expansion` != `expanding relative paths to absolute path equivalent`. 

Code path before:
1. str input - Python (no action) + Rust (coerce to absolute path)
2. Path object input - Python (coerce to absolute path) + Rust (coerce to absolute path)

Code path now:
1. str / Path object input - Python (no action) + Rust (tilde expansion + coerce to absolute path).

**Review by changhiskhan — COMMENTED** [review]
Thanks. This looks fine. Can you just add two quick unit tests to check that tilde expansion and relative paths work *from python*?

**Comment by ananis25** [comment]
Added test to check relative paths work. 

I can't think of a clean way to check for tilde expansion from python, without writing to the user's home directory. Is there a workaround?

**Comment by changhiskhan** [comment]
> Added test to check relative paths work.
> 
> I can't think of a clean way to check for tilde expansion from python, without writing to the user's home directory. Is there a workaround?

For example:

```
def test_home(tmp_path):
    with mock.patch.dict(os.environ, {"HOME": str(tmp_path)}):
        print(f"tmp_path is {tmp_path}")
        print(f"HOME is {os.environ['HOME']}")
        print(f"~ is {pathlib.Path('~').expanduser()}")
    print(f"HOME is {os.environ['HOME']}")
    print(f"~ is {pathlib.Path('~').expanduser()}")
```

the first 3 prints:

```
python/tests/test_dataset.py tmp_path is /private/var/folders/p6/0wtfjg9d4bsd59fl0v2zgy3c0000gn/T/pytest-of-changshe/pytest-72/test_home0
HOME is /private/var/folders/p6/0wtfjg9d4bsd59fl0v2zgy3c0000gn/T/pytest-of-changshe/pytest-72/test_home0
~ is /private/var/folders/p6/0wtfjg9d4bsd59fl0v2zgy3c0000gn/T/pytest-of-changshe/pytest-72/test_home0
```

the last 2 prints:
```
HOME is /Users/changshe
~ is /Users/changshe
```

**Comment by ananis25** [comment]
Added.

**Review by changhiskhan — APPROVED** [review]
Nice. Thanks!

**Pull request merged**
