### PR TITLE
Commit for testing

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Please don't close the PR. I have committed to testing. Please ask me once if any modification require, I will do. If it can't work, please don't close the PR, keep it open.

### CODE REVIEW

**Comment by eddyxu** [comment]
Thanks for the contribution @tarunsamanta2k20 

It turns out that our Github Action is not triggering.

Could you also modified
https://github.com/eto-ai/lance/blob/175bc471c49a9ba8f3709ef4c12690e8ec53699a/.github/workflows/rust.yml#L6-L9

To make sure the CI will be triggered if the github action yaml file is modified?

**Comment by changhiskhan** [comment]
Are you still working on this? If not can i close it?

**Comment by changhiskhan** [comment]
This has been stale for more than month. I'd like to close it if it's not being actively worked on. Please lmk. Thanks!

**Comment by tarunsamanta2k20** [comment]
@changhiskhan let me check once.

**Comment by changhiskhan** [comment]
closing due to inactivity

**Pull request closed without merging**
